# Generated by Django 5.1.4 on 2024-12-10 02:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_rename_contents_board_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='writer',
            field=models.CharField(default='default_writer', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
