services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: naver_news
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # 로컬에서 3307 포트로 변경
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


  app:
    build: .
    container_name: flask_app
    depends_on:
      - db
    volumes:
      - ./app:/app
      - ./logs:/logs
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=naver_news
      - MYSQL_PORT=3307
